import django
from django.utils import unittest
from django.test import TestCase
from django.test.client import Client
from website.models import User, RatingCategory, ActionCategory, Jurisdiction, Question, AnswerReference
from django.contrib.auth import authenticate
from django.conf import settings
import json
from itertools import chain
from pprint import pprint
import lxml
import lxml.html
import lxml.etree

class TestAnswering(TestCase):
    #fixtures = ['questions']
    def setUp(self):
        self.users = [User.objects.create_user("testuser%s" % id, "testuser%s@testing.solarpermit.org" % id, "testuser")
                          for id in xrange(3)]
        self.ahj = [Jurisdiction.objects.create(city = "foo city",
                                                name_for_url = "foo",
                                                description = "foo",
                                                state = "CA",
                                                jurisdiction_type = "CI",
                                                name = "foo"),
                    Jurisdiction.objects.create(city = "bar city",
                                                name_for_url = "bar",
                                                description = "bar",
                                                state = "CA",
                                                jurisdiction_type = "CI",
                                                name = "bar")]

    """
    select id, form_type as type, support_attachments as attach, has_multivalues as multi, default_value, display_template from website_question where accepted = 1 and form_type != 'CF' group by type, attach, multi, def
ault_value, display_template order by display_template;
    |-----+------+-----+------+-----------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    |  id | type | att | mult | display_template                                                      | default_value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    |-----+------+-----+------+-----------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    |   1 | T    |   0 |    0 | NULL                                                                  | {"value":""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    |  15 | MF   |   0 |    0 | NULL                                                                  | {"value":"no"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    |  51 | TA   |   0 |    1 | NULL                                                                  | {"value":""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    |  57 | TA   |   0 |    0 | NULL                                                                  | {"value":""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    | 102 | MF   |   0 |    0 | NULL                                                                  | {"value":""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    |   4 | MF   |   0 |    0 | address_display.html                                                  | {"city": "", "state": "", "zip_code": "", "address2": "", "address1": "", "county": "" }                                                                                                                                                                                                                                                                                                                                                                                                                             |
    |  14 | MF   |   0 |    0 | available_url_display.html                                            | {"available":"no", "url":""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    |  69 | MF   |   0 |    0 | fire_setbacks_display.html                                            | {"note": "", "enforced": "No", "system_rating_method": "", "equality": "greater than", "kW": "", "url_or_email_for_submissions": "url"  }                                                                                                                                                                                                                                                                                                                                                                            |
    |  64 | MF   |   0 |    0 | homeowner_requirements_display.html                                   | {"note": "", "disclose_issue": "", "disclose_communication": ""}                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
    |   8 | MF   |   0 |    0 | hours_display.html                                                    | {"to_min": "00", "to_hour": "5", "from_am_pm": "am", "to_am_pm": "pm", "from_min": "00", "from_hour": "9"}                                                                                                                                                                                                                                                                                                                                                                                                           |
    | 105 | MF   |   1 |    1 | inspection_checklists_display.html                                    | {"available":"no", "value":"", "form_option": "link", "link_1": "", "name_1": ""}                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | 282 | MF   |   1 |    1 | online_forms.html                                                     | {"form_option": "link", "link_1": "", "name_1": ""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    |  16 | MF   |   0 |    0 | permit_cost_display.html                                              | {"fee_type_1": "fee type", "fee_item_1_1": "fee item", "fee_formula_1_1": "flat_rate", "fee_other_1_1": "", "fee_percentage_of_total_system_cost_cap_1_1": "", "fee_per_inverter_1_1": "0", "fee_flat_rate_1_1": "", "fee_per_major_components_1_1": "0", "fee_jurisdiction_cost_recovery_notes_1_1": "", "fee_percentage_of_total_system_cost_1_1": "", "fee_percentage_of_total_system_cost_cap_amt_1_1": "", "fee_per_component_cap_1_1": "", "fee_per_component_cap_cap_amt_1_1": "", "fee_per_module_1_1": "0"} |
    |   2 | MF   |   0 |    0 | phone_display.html                                                    | {"phone": "", "ext": ""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    |  97 | MF   |   0 |    0 | plan_check_service_type_display.html                                  | {"note": "", "plan_check_service_type": "Over the counter"}                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    |  43 | MF   |   0 |    0 | radio_allowed_with_exception_display.html                             | {"note": "", "allowed": "No", "system_rating_method": "", "equality": "greater than", "kW": "", "url_or_email_for_submissions": "url"  }                                                                                                                                                                                                                                                                                                                                                                             |
    | 104 | MF   |   0 |    0 | radio_available_with_exception_display.html                           | {"note": "", "available": "No", "system_rating_method": "", "equality": "greater than", "kW": "", "url_or_email_for_submissions": "url"  }                                                                                                                                                                                                                                                                                                                                                                           |
    | 283 | MF   |   0 |    0 | radio_compliant_sb1222_with_exception.html                            | {"compliant": "yes" }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
    |  33 | MF   |   0 |    0 | radio_covered_with_exception_display.html                             | {"note": "", "allowed": "No", "system_rating_method": "", "equality": "greater than", "kW": "", "min_distance": "", "url_or_email_for_submissions": "url"  }                                                                                                                                                                                                                                                                                                                                                         |
    | 111 | MF   |   0 |    0 | radio_has_training_display.html                                       | {"value":"no"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    |  81 | MF   |   0 |    0 | radio_inspection_approval_copies_display.html                         | {"apply":"in person", "request_by_phone":"", "request_by_fax":"", "request_by_email":"","phone":"", "fax":"", "email":""}                                                                                                                                                                                                                                                                                                                                                                                            |
    | 112 | MF   |   0 |    0 | radio_licensing_required_display.html                                 | {"note": "", "required": "No"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    |  36 | MF   |   1 |    1 | radio_module_drawings_display.html                                    | {"value":"must draw individual modules", "form_option": "link", "link_1": "", "name_1": ""}                                                                                                                                                                                                                                                                                                                                                                                                                          |
    |  22 | MF   |   0 |    0 | radio_required_display.html                                           | {"value":"Not required"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    |  17 | MF   |   0 |    0 | radio_required_for_page_sizes_display.html                            | {"required": "no", "size": "", "width": "", "height": ""  }                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    |  18 | MF   |   0 |    0 | radio_required_for_scales_display.html                                | {"scale": "any", "scale_factor": "1:1", "scale_factor_1": "", "scale_factor_2": ""  }                                                                                                                                                                                                                                                                                                                                                                                                                                |
    |  35 | MF   |   0 |    0 | radio_studer_vent_rules_with_exception_display.html                   | {"note": "", "allowed": "No", "system_rating_method": "", "equality": "greater than", "kW": "", "url_or_email_for_submissions": "url"  }                                                                                                                                                                                                                                                                                                                                                                             |
    |   5 | MF   |   0 |    0 | radio_submit_PE_stamped_structural_letter_with_exception_display.html | {"note": "", "required": "No", "system_rating_method": "", "equality": "greater than", "kW": "", "dead_load_calculations": "No", "url_or_email_for_submissions": "url"  }                                                                                                                                                                                                                                                                                                                                            |
    |  92 | MF   |   0 |    0 | radio_vent_spanning_rules_with_exception_display.html                 | {"note": "", "allowed": "No", "system_rating_method": "", "equality": "greater than", "kW": "", "url_or_email_for_submissions": "url"  }                                                                                                                                                                                                                                                                                                                                                                             |
    |  19 | MF   |   0 |    0 | radio_with_exception_display.html                                     | {"note": "", "required": "No", "system_rating_method": "", "equality": "greater than", "kW": "", "url_or_email_for_submissions": "url"  }                                                                                                                                                                                                                                                                                                                                                                            |
    |  63 | MF   |   0 |    0 | radio_with_exception_display.html                                     | {"note": "", "required": "No", "system_rating_method": "", "equality": "greater than", "kW": "" , "url_or_email_for_submissions": "url" }                                                                                                                                                                                                                                                                                                                                                                            |
    |  73 | MF   |   0 |    0 | radio_with_exception_display.html                                     | {"note": "", "required": "No"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    |  62 | MF   |   1 |    1 | required_spec_sheets_display.html                                     | {"value":"","form_option": "link", "link_1": "", "name_1": ""}                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    |  85 | MF   |   0 |    0 | signed_inspection_approval_delivery_display.html                      | {"mail":"", "email":"", "onsite":""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
    |  96 | MF   |   1 |    1 | solar_permitting_checklists_display.html                              | {"available":"no", "url":"", "form_option": "link", "link_1": "", "name_1": ""}                                                                                                                                                                                                                                                                                                                                                                                                                                      |
    | 107 | MF   |   0 |    0 | time_window_display.html                                              | {"note": "", "time_window": "8"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
    |   9 | MF   |   0 |    0 | turn_around_time_display.html                                         | {"note": "", "time_unit": "hour(s)", "time_qty": "1"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
    |   3 | T    |   0 |    0 | url.html                                                              | {"value":""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    |   6 | MF   |   0 |    1 | url.html                                                              | {"link_1": "", "name_1": ""}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    |-----+------+-----+------+-----------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    """

    def test(self):
        tests = {   1: [({ 'field_value': 'test answer' },
                         '//div[@class="field answer_field"]/div[normalize-space(text())="Test answer"]')],
                   15: [({ 'field_value': 'test answer' },
                         '//div[@class="field answer_field"]/div[normalize-space(text())="Test answer"]')],
                   51: [({ 'field_value': 'test answer' },
                         '//div[@class="field answer_field"]/div[normalize-space(text())="Test answer"]')],
                   57: [({ 'field_value': 'test answer' },
                         '//div[@class="field answer_field"]/div[normalize-space(text())="Test answer"]')],
                   102: [({ 'field_value': 'test answer' },
                         '//div[@class="field answer_field"]/div[normalize-space(text())="Test answer kW"]')],
                     4: [({ 'field_address1': '123 Main St',
                            'field_address2': 'Suite 42',
                            'field_city': 'Nowhere',
                            'field_state': 'CA',
                            'field_zip_code': '12345',
                            'field_county': '' },
                          '//div[@class="field answer_field"]/div[normalize-space(text())="123 Main St, Suite 42, Nowhere, CA 12345"]')], }

        for (qid, scenarios) in tests.iteritems():
            print("testing question %s" % qid)
            for (scenario, result) in scenarios:
                self.do_answer(self.ahj[0], Question.objects.get(id=qid), scenario, result)

    def do_answer(self, ahj, question, scenario, result):
        self.client = Client()
        self.assertIsNotNone(question)
        (status_code, content) = post(self.client, ahj, question, scenario)
        self.assertEqual(401, status_code)
        logged_in = self.client.login(username='testuser0',
                                      password='testuser')
        self.assertTrue(logged_in)
        (status_code, content) = post(self.client, ahj, question, scenario)
        self.assertEqual(200, status_code)
        self.assertTemplateUsed(question.display_template or 'single_field_display.html')
        self.assertContainsXPath(content[0]['val'], result)

    def assertContainsXPath(self, html_haystack, xpath_needle):
        parsed = lxml.html.fragment_fromstring(html_haystack,
                                               lxml.etree.HTMLParser(recover=True,
                                                                     remove_blank_text=True))
        nodes = []
        try:
            nodes = parsed.xpath(xpath_needle)
        except Exception as e:
            print(e)
            pass
        self.assertTrue(len(nodes) > 0,
                        '"'+ xpath_needle +'" should match\n'+ lxml.etree.tostring(parsed,
                                                                                   pretty_print=True,
                                                                                   method="html"))

def post(client, ahj, question, data):
    res = client.post('/jurisdiction/%s/' % ahj.name_for_url,
                      dict(chain(data.iteritems(),
                                 { 'ajax': 'suggestion_submit',
                                   'jurisdiction_id': ahj.id,
                                   'question_id': question.id }.iteritems())))
    return (res.status_code, try_decode(res.content))

def try_decode(content):
    try:
        return json.loads(content)
    except:
        return None
